### ISSUE TITLE
Gateway is unable to get clusterId

### ISSUE THREAD

**Issue by shayfisher** [aquasecurity/aqua-helm#41]
Gateway is unable to get ClusterId according to the logfile while using the server chart:
2019-07-10 07:29:17.172 WARN    Failed getting cluster id, failed getting nodes: nodes is forbidden: User "system:serviceaccount:aqua:aqua-sa" cannot list resource "nodes" in API group "" at the cluster scope

Here is the fix:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-cluster-role
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: ["extensions"]
  resourceNames: [{{ .Release.Name }}-psp]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
{{- end }}

```
