### ISSUE TITLE
HTTP proxy env variables for air-gapped outbound connections

### ISSUE THREAD

**Issue by ap0phi5** [aquasecurity/aqua-helm#44]
Need to add [no_]http_proxy[s] variables to server to allow connectivity to CyberCentre from  air-gapped environments.

```
    spec:
      containers:
        env:
        - name: http_proxy
          value: "$proxy_url"
        - name: https_proxy
          value: "$proxy_url"
        - name: no_proxy
          value: "$noproxy"
```
