### ISSUE TITLE
tolerations is not templated correctly

### ISSUE THREAD

**Issue by vikas027** [aquasecurity/aqua-helm#451]
It looks like [tolerations](https://github.com/aquasecurity/aqua-helm/blob/6.5/enforcer/values.yaml#L101) has no effect, I had defined it as below but it did not appeared in the `daemonset` or the `pod`

```
tolerations:
- key: somekey
  value: somevalue
  effect: NoSchedule
```
