### ISSUE TITLE
Enforcer Toleration still not working

### ISSUE THREAD

**Issue by Volkimd** [aquasecurity/aqua-helm#475]
I am using Enforcer Chart Version 6.5.5.

There seems to be still a problem. No tolerations will appear. 

I set it like:

```
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    effect: "NoSchedule"
    operator: "Exists"
  - key: "node-role.kubernetes.io/etcd"
    effect: "NoExecute"
    operator: "Exists"
  - key: "nvidia.com/gpu"
    effect: "NoSchedule"
    operator: "Exists"
```

nothing appears in daemonset manifest
