### ISSUE TITLE
Helm chart deployment returns error

### ISSUE THREAD

**Issue by rgarcia89** [aquasecurity/aqua-helm#495]
https://github.com/aquasecurity/aqua-helm/blob/4f1c0cd56801f1d6c2b58ea6db66607628de1db6/enforcer/templates/enforcer-daemonset.yaml#L27

```
Error: YAML parse error on enforcer/templates/enforcer-daemonset.yaml: error converting YAML to JSON: yaml: line 27: could not find expected ':'
helm.go:88: [debug] error converting YAML to JSON: yaml: line 27: could not find expected ':'
YAML parse error on enforcer/templates/enforcer-daemonset.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        helm.sh/helm/v3/pkg/action/action.go:165
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
        helm.sh/helm/v3/pkg/action/install.go:259
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:267
main.newTemplateCmd.func2
        helm.sh/helm/v3/cmd/helm/template.go:82
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_amd64.s:1581
```

**Comment by semyonmor** [comment]
@rgarcia89 
Which command did you use for deployment?

**Comment by rgarcia89** [comment]
@semyonmor the problem comes because of the serviceAccount template
You can see a line break before.

```yaml
# Source: enforcer/templates/enforcer-daemonset.yaml

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aqua-enforcer-ds
  namespace: aqua
  labels:
    app: aqua-enforcer-ds
    chart: "enforcer-6.5.6"
    release: "aqua-enforcer"
    heritage: "Helm"
spec:
  selector:
    matchLabels:
      app: aqua-enforcer-ds
  template:
    metadata:
      annotations:
        checksum/config: 75796d36eeb72dfd6c0b4fb
        container.apparmor.security.beta.kubernetes.io/enforcer: unconfined
      labels:
        app: aqua-enforcer-ds
      name: aqua-enforcer-ds
    spec:
      serviceAccount:
aqua-sa
```

```yaml
# Source: enforcer/templates/serviceaccount.yaml

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:
aqua-sa
  namespace: aqua
  labels:
    app: aqua-enforcer
    chart: "enforcer-6.5.6"
    release: "aqua-enforcer"
    heritage: "Helm"
imagePullSecrets:
- name: aqua-registry-secret
```
