### ISSUE TITLE
Image Pull Secret key stays empty even being defined

### ISSUE THREAD

**Issue by rgarcia89** [aquasecurity/aqua-helm#497]
https://github.com/aquasecurity/aqua-helm/blob/f566bfdd3558ec6a8973f9933e28924f18c72e70/enforcer/templates/serviceaccount.yaml#L14

```
imageCredentials:
  create: false
  name: aqua-registry # When create is false please specify
  repositoryUriPrefix: "registry.aquasec.com" # for dockerhub - "docker.io"
  registry: "registry.aquasec.com" #REQUIRED only if create is true, for dockerhub - "index.docker.io/v1/"
  username: ""
  password: ""
```

```
---
# Source: enforcer/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aqua-sa
  namespace: aqua
  labels:
    app: aqua-enforcer
    chart: "enforcer-6.5.6"
    release: "aqua-enforcer"
    heritage: "Helm"
imagePullSecrets:
- name:
```
