### ISSUE TITLE
Multiple 'app.kubernetes.io/managed-by' label entries create invalid manifests

### ISSUE THREAD

**Issue by hobaen** [aquasecurity/aqua-helm#608]
Chart: kube-enforcer
Chart Version: 2022.4.0

Expected: When helm renders the templates, `configauditreports.aquasecurity.github.io` and `clusterconfigauditreports.aquasecurity.github.io` CRDs only have a single `app.kubernetes.io/managed-by` label.

Observed: When helm renders the templates, `configauditreports.aquasecurity.github.io` and `clusterconfigauditreports.aquasecurity.github.io` CRDs  have two `app.kubernetes.io/managed-by` labels, thus failing helm release validation when used with Flux 2.

Taken from `helm template` output:
```
# Source: kube-enforcer/templates/custom-resorce-defination.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configauditreports.aquasecurity.github.io
  namespace: system
  labels:
    role: RELEASE-NAME
    app.kubernetes.io/managed-by: starboard
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: 'kube-enforcer-2022.4.0'
...
# Source: kube-enforcer/templates/custom-resorce-defination.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterconfigauditreports.aquasecurity.github.io
  labels:
    role: RELEASE-NAME
    app.kubernetes.io/managed-by: starboard
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: 'kube-enforcer-2022.4.0'
```

Notes:
first `app.kubernetes.io/managed-by` defined at https://github.com/aquasecurity/aqua-helm/blob/2022.4/kube-enforcer/templates/custom-resorce-defination.yaml#L9 , then the next line pulls in `aqua.labels` which in turn pulls in `aqua.template-labels` https://github.com/aquasecurity/aqua-helm/blob/2022.4/kube-enforcer/templates/_helpers.tpl#L115 which in turn has a second `app.kubernetes.io/managed-by`

Additionally, as a less important side note, the file name is currently `custom-resorce-defination` instead of `custom-resource-definition`
