### ISSUE TITLE
Bug: Failed to pull enforcer image when using private registry

### ISSUE THREAD

**Issue by rswrz** [aquasecurity/aqua-helm#625]
Recently, I updated an Aqua deployment from version `6.5` to `2022.4.81`. That deployment consists of server, gateway, scanner and enforcer.

Unfortunately, the update deployment failed. The reason was that the enforcer image cloud not be pulled, server, gateway and scanner had no issues. I use a private container registry, where I did push all necessary container images into. After some investigating, I found out, that the enforcer DaemonSet was trying to pull the container image from the official but private Aqua image registry, other than set in my `values.yaml` .

For the server, gateway and scanner charts, the private registry is set like this in my umbrella chart`values.yaml`:

```yaml
server:
  imageCredentials:
    repositoryUriPrefix: "my-private-container-registry.io"
  gateway:
    imageCredentials:
      repositoryUriPrefix: "my-private-container-registry.io"
scanner:
  imageCredentials:
    repositoryUriPrefix: "my-private-container-registry.io"
```

It is also the case for the enforcer chart, but does not work anymore.

```yaml
enforcer:
  imageCredentials:
    repositoryUriPrefix: "my-private-container-registry.io"
```

A quick workaround was to set a global value in my `values.yaml`, which is now used by the enforcer chart templates.

```yaml
global:
  imageCredentials:
    create: false
    repositoryUriPrefix: "my-private-container-registry.io"
```

👉 The reason for this is [this change](https://github.com/aquasecurity/aqua-helm/pull/558/commits/bca0d75d244f6d25ad3cbd03dd8711dd7fbe301e#diff-97f88a5bfa165d545426de598f25893fa2e1b960f887d054b6612593282ce269L43-R43). I think it was a mistake. When I am wrong, I am happy to be clarified about it.
