### ISSUE TITLE
server web secret issue

### ISSUE THREAD

**Issue by ahmei0** [aquasecurity/aqua-helm#721]
server/values.yaml  server/templates/web-secret.yaml and server/templates/web-deployment.yaml are current written such way that  if following values are set then it creates a secret. There is no way to use existing secret and no way to pass secret name

```
admin:
  token: ""
  password: ""
```
I need it changed such that I can use a pre existing secret instead of creating one through template, values file should look something like this

```
adminCredentials:
  enabled: true
  create: false
  name: aqua-console-secrets
  token: ""
  password: ""
```
