### ISSUE TITLE
Need ability to annotate services

### ISSUE THREAD

**Issue by kcorupe** [aquasecurity/aqua-helm#92]
AWS requires annotation of services for certain configurations as an example requirement.

This PR was closed that added that functionality without comment.

https://github.com/aquasecurity/aqua-helm/pull/79

Example:
```
  grpcservice:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: aqua-gateway.company.domain
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```
